--- #YAML:1.0
name:               JSON-RPC-Common
version:            0.04
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Request:     0
    JSON:              2.11
    MIME::Base64:      0
    Moose:             0.48
    MooseX::Types:     0
    namespace::clean:  0.08
    Test::Exception:   0
    Test::use::ok:     0
    URI::QueryParam:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
