--- #YAML:1.0
name:                JSON-RPC-Common
version:             0.03
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    HTTP::Request:                 0
    JSON:                          0
    MIME::Base64:                  0
    Moose:                         0.48
    MooseX::Types:                 0
    namespace::clean:              0.08
    Test::Exception:               0
    Test::use::ok:                 0
    URI::QueryParam:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
